### PR TITLE
Device

### PR DESCRIPTION
**Pull request by simonmika**
Added a `devices` menu item where documentation about all Vidhance enabled devices go and added a stub article for Huawei Mate 9.

### CODE REVIEW

**Comment by simonmika** [comment]
@vvizard- What do you think about this? The Mate 9 article is just a place holder of sorts. I think it might be better do have one article per phone containing Vidhance then to have one big one.

**Comment by vvizard-** [comment]
Actually I don't think it's a good idea. The reason being that hopefully vidhance will be in so many models, it will be lots of work writing those articles. And for lots of models, they will probably remain stubs. Probably with little more than a link to a product page and maybe a review. 

For example, BQ already have three VH phones. And they're launching four new models this Tuesday, where none or four might get VH. 
It could also give an expectation that we will figure out all the models with VH in the future. And we might not be able to do that anymore, if the amount gets big enough.

I think it's easiest to have a list of known models, and the flexibility to choose how to handle the details. For example one general article for Huawei, but in the future maybe do an own article for Mate or P-series (for example) but still having flexibility to just have one article for BQ, as their individual models probably don't deserve a whole article on its own.

It all needs to be written/updated, and I'm afraid the task will become to daunting to do it for every model.

**Comment by simonmika** [comment]
@vvizard- your points are are valid. The question is if we still should maybe have an article per device maker or so under a separate menu item like this? When needed articles for product lines or individual products can of course also be created.

**Comment by simonmika** [comment]
@vvizard- so what do you think about this? I think this level is doable. At least for the comming year or so. Should the menu item be called *customers*?

**Comment by vvizard-** [comment]
Yes, i think this could work! Good job! And sorry for the delay in answering on this change.

**Comment by simonmika** [comment]
24 minutes is a fast response. I'll go ahead and publish it. Feel free to amend and change things. Especially it would be great to not only have the date the models where announced but when sales actually started as that is what most of the time is affecting Imint's bottom line.

**Comment by simonmika** [comment]
Should we remove the article http://localhost:1313/article/20170915-imint-customers-and-products/ or keep it for now?

**Pull request merged**
