### PR TITLE
Fixed links.

### PR DESCRIPTION
**Pull request by simonmika**

### CODE REVIEW

**Comment by vvizard-** [comment]
What's the reason for this? Should I stop using brackets when using link-references in md?

**Comment by simonmika** [comment]
Yes you should. Sorry for not pinging you. Zeebz found it.

**Comment by vvizard-** [comment]
Ok I will. What's the difference between brackets and not?

**Comment by simonmika** [comment]
The last bracket is added to the url and will break the link. It might work in Github-flavored markup but this Hugo program is using some Go library so that might be the reason.

**Comment by vvizard-** [comment]
Ok understand. Noted.

**Pull request merged**
